name: Build on Main Push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Build Package
        run: poetry build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
