name: Test, Format, Version Bump

on:
  push:
    branches:
      - test

permissions:
  contents: write
  id-token: write

jobs:
  format-bump-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Format Code
        run: |
          black .
          isort .

      - name: Commit Formatting
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "🤖 Auto-format"
          git push
        continue-on-error: true

      - name: Bump Version
        run: |
          poetry version patch
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pyproject.toml
          git commit -m "🔖 Bump version"
          git push
        continue-on-error: true

